version: "3"

services:
  endpoint1:
    image: 21re/coding-challenge:latest
    ports:
      - "8080:80"
  endpoint2:
    image: theapi:SNAPSHOT
    environment:
      - APP_REMOTE=http://endpoint1:80
    ports:
      - "1337:1337"
        #networks:
        #    default:
        #          driver: bridge
