version: "3"

services:
  endpoint1:
    image: <YOUR IMAGE HERE>
    ports:
      - "8080:80"
  endpoint2:
    image: theapi:SNAPSHOT
    environment:
      - APP_REMOTE=http://endpoint1:80
    ports:
      - "1337:1337"
